# Generated by Django 4.2.7 on 2024-01-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_pub_date_alter_ingredientcount_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favrecipes',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='favrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_recipes', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
